// =====================================================
// Odinote — Sample Templates & Translations Data
// Showcasing Architecture, Game Design, and Marketing
// =====================================================

const SAMPLE_PROJECTS = [
  {
    id: 'architecture',
    name: { es: 'Estudio de Arquitectura — Casa Colina', en: 'Architecture Studio — Hillside House' },
    emoji: '🏡',
    cover: 'linear-gradient(135deg, #A8E6C9, #DFF26E)',
    updated: { es: 'hace 2 horas', en: '2 hours ago' },
    items: 7,
  },
  {
    id: 'gamedev',
    name: { es: 'Diseño de Videojuego — Project Aether', en: 'Game Design — Project Aether' },
    emoji: '👾',
    cover: 'linear-gradient(135deg, #D4B4FF, #FFB088)',
    updated: { es: 'ayer', en: 'yesterday' },
    items: 7,
  },
  {
    id: 'marketing',
    name: { es: 'Campaña de Marketing — Lanzamiento Nova', en: 'Marketing Campaign — Nova Launch' },
    emoji: '🚀',
    cover: 'linear-gradient(135deg, #FFB6D4, #FFD0E5)',
    updated: { es: 'hace 3 días', en: '3 days ago' },
    items: 7,
  },
];

// All canvases live in one big map. Root canvas key = project id.
// Boards are first-class items with their own canvas key.
const INITIAL_CANVASES = {
  // ─────────── 1. ARCHITECTURE ───────────
  'architecture': {
    title: { es: 'Estudio de Arquitectura — Casa Colina', en: 'Architecture Studio — Hillside House' },
    items: [
      {
        id: 'arch-note-1', type: 'note', x: 60, y: 130, w: 460, h: 80, color: 'mint',
        content: {
          es: '🏡 **Estudio preliminar - Casa Colina**\nDiseño ecológico de bajo impacto energético, adaptado a la topografía de la ladera oeste.',
          en: '🏡 **Preliminary study - Hillside House**\nLow-energy ecological design, adapted to the topography of the western hillside.',
        },
      },
      {
        id: 'arch-board-1', type: 'board', x: 60, y: 240, w: 260, h: 180, color: 'sky',
        canvasId: 'arch-plans',
        content: { es: 'Zonificación y Planos', en: 'Zoning & Blueprints' },
      },
      {
        id: 'arch-board-2', type: 'board', x: 340, y: 240, w: 260, h: 180, color: 'cream',
        canvasId: 'arch-materials',
        content: { es: 'Materiales y Acabados', en: 'Materials & Finishes' },
      },
      {
        id: 'arch-col-1', type: 'column', x: 60, y: 450, w: 280, h: 320, color: 'coral',
        content: { es: 'Fases del Proyecto', en: 'Project Phases' },
        children: [
          { id: 'ap1', text: { es: 'Fase 1: Levantamiento 3D', en: 'Phase 1: 3D Survey' } },
          { id: 'ap2', text: { es: 'Fase 2: Anteproyecto', en: 'Phase 2: Concept Design' } },
          { id: 'ap3', text: { es: 'Fase 3: Ingeniería Estructural', en: 'Phase 3: Structural Engineering' } },
        ],
      },
      {
        id: 'arch-todo-1', type: 'todo', x: 360, y: 450, w: 280, h: 220, color: 'yellow',
        title: { es: 'Pendientes', en: 'Tasks' },
        items: [
          { id: 'at1', text: { es: 'Verificar distancias reglamentarias', en: 'Check zoning setbacks' }, done: true },
          { id: 'at2', text: { es: 'Selección de vidrios fotovoltaicos', en: 'Select photovoltaic glass' }, done: false },
          { id: 'at3', text: { es: 'Reunión con paisajista', en: 'Meeting with landscape designer' }, done: false },
        ],
      },
      {
        id: 'arch-cmt-1', type: 'comment', x: 640, y: 240, w: 260, h: 120,
        avatar: 'M', avatarColor: 'sky',
        name: 'Arq. Mateo',
        text: {
          es: 'La inclinación de la ladera requiere un muro de contención reforzado en el eje norte.',
          en: 'The slope inclination requires a reinforced retaining wall on the north axis.',
        },
      },
      {
        id: 'arch-palette', type: 'swatch', x: 640, y: 390, w: 260, h: 140,
        title: { es: 'Paleta Orgánica', en: 'Organic Palette' },
        colors: [
          { hex: '#3E5C4E', name: 'Pino' },
          { hex: '#D2B48C', name: 'Arena' },
          { hex: '#705A4E', name: 'Piedra' },
          { hex: '#FAF9F6', name: 'Tiza' },
        ],
      },
    ],
    connectors: [
      { id: 'ac1', from: 'arch-note-1', to: 'arch-board-1', fromAnchor: 'bottom', toAnchor: 'top', bend: { x: -40, y: 0 } },
    ],
  },
  'arch-plans': {
    title: { es: 'Zonificación y Planos', en: 'Zoning & Blueprints' },
    parent: 'architecture',
    parentLabel: { es: 'Casa Colina', en: 'Hillside House' },
    items: [
      {
        id: 'arch-plans-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Planos y Distribución', en: 'Blueprints & Distribution' },
      },
      {
        id: 'arch-plans-n1', type: 'note', x: 60, y: 130, w: 260, h: 160, color: 'sky',
        content: {
          es: '**PLANTA BAJA**\n- Estacionamiento techado (2 autos)\n- Hall de acceso de doble altura\n- Cocina y comedor abierto\n- Terraza con borde infinito',
          en: '**GROUND FLOOR**\n- Covered parking (2 cars)\n- Double height access hall\n- Open kitchen & dining room\n- Infinity edge terrace',
        },
      },
      {
        id: 'arch-plans-n2', type: 'note', x: 340, y: 130, w: 260, h: 160, color: 'mint',
        content: {
          es: '**PLANTA ALTA**\n- Suite principal + vestidor\n- Biblioteca / Oficina en casa\n- 2 dormitorios secundarios con baño',
          en: '**FIRST FLOOR**\n- Master suite + walk-in closet\n- Library / Home office\n- 2 secondary bedrooms with bathroom',
        },
      },
    ],
    connectors: [],
  },
  'arch-materials': {
    title: { es: 'Materiales y Acabados', en: 'Materials & Finishes' },
    parent: 'architecture',
    parentLabel: { es: 'Casa Colina', en: 'Hillside House' },
    items: [
      {
        id: 'arch-mat-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Materiales Sugeridos', en: 'Suggested Materials' },
      },
      {
        id: 'arch-mat-n1', type: 'note', x: 60, y: 130, w: 260, h: 150, color: 'cream',
        content: {
          es: '**Fachada y Exteriores**\n- Hormigón visto texturizado\n- Paneles de madera de teca curada\n- Piedra volcánica local en la base',
          en: '**Facade & Exteriors**\n- Textured exposed concrete\n- Cured teak wood panels\n- Local volcanic stone at the base',
        },
      },
      {
        id: 'arch-mat-n2', type: 'note', x: 340, y: 130, w: 260, h: 150, color: 'yellow',
        content: {
          es: '**Interiores y Pisos**\n- Microcemento gris claro\n- Revestimientos en madera de roble\n- Griferías empotradas negro mate',
          en: '**Interiors & Floors**\n- Light gray microcement\n- Oak wood paneling\n- Matte black built-in faucets',
        },
      },
    ],
    connectors: [],
  },

  // ─────────── 2. GAME DESIGN ───────────
  'gamedev': {
    title: { es: 'Diseño de Videojuego — Project Aether', en: 'Game Design — Project Aether' },
    items: [
      {
        id: 'game-note-1', type: 'note', x: 60, y: 130, w: 460, h: 80, color: 'lavender',
        content: {
          es: '👾 **Project Aether (Metroidvania)**\nJuego de acción y exploración 2D. Enfoque en combos aéreos y personalización de prótesis mecánicas.',
          en: '👾 **Project Aether (Metroidvania)**\n2D action-exploration game. Focus on aerial combos and mechanical prosthetic customization.',
        },
      },
      {
        id: 'game-board-1', type: 'board', x: 60, y: 240, w: 260, h: 180, color: 'pink',
        canvasId: 'game-chars',
        content: { es: 'Personajes y Jefes', en: 'Characters & Bosses' },
      },
      {
        id: 'game-board-2', type: 'board', x: 340, y: 240, w: 260, h: 180, color: 'mint',
        canvasId: 'game-mechs',
        content: { es: 'Mecánicas Core', en: 'Core Mechanics' },
      },
      {
        id: 'game-col-1', type: 'column', x: 60, y: 450, w: 280, h: 320, color: 'coral',
        content: { es: 'Sprint Backlog', en: 'Sprint Backlog' },
        children: [
          { id: 'gp1', text: { es: 'Pulir salto y aceleración física', en: 'Polish jump & physics acceleration' } },
          { id: 'gp2', text: { es: 'Efectos de sonido de impacto', en: 'Hit impact sound effects' } },
          { id: 'gp3', text: { es: 'Diseño del Jefe: El Alquimista', en: 'Boss Design: The Alchemist' } },
        ],
      },
      {
        id: 'game-todo-1', type: 'todo', x: 360, y: 450, w: 280, h: 220, color: 'yellow',
        title: { es: 'Hitos Alpha', en: 'Alpha Milestones' },
        items: [
          { id: 'gt1', text: { es: 'Implementar el doble salto rúnico', en: 'Implement runic double jump' }, done: true },
          { id: 'gt2', text: { es: 'Integrar enemigo básico (Cazador)', en: 'Integrate basic enemy (Scout)' }, done: false },
          { id: 'gt3', text: { es: 'Prueba de control con Gamepad', en: 'Gamepad controller test' }, done: false },
        ],
      },
      {
        id: 'game-cmt-1', type: 'comment', x: 640, y: 240, w: 260, h: 120,
        avatar: 'N', avatarColor: 'pink',
        name: 'Niko (Gamedev)',
        text: {
          es: '¿Y si el gancho consume vapor de presión en vez de energía rúnica?',
          en: 'What if the grappling hook consumes pressure steam instead of runic energy?',
        },
      },
      {
        id: 'game-palette', type: 'swatch', x: 640, y: 390, w: 260, h: 140,
        title: { es: 'Paleta Steampunk', en: 'Steampunk Palette' },
        colors: [
          { hex: '#4A3B32', name: 'Cobre' },
          { hex: '#D4AF37', name: 'Bronce' },
          { hex: '#7D2E68', name: 'Aether' },
          { hex: '#1A1A1A', name: 'Hollín' },
        ],
      },
    ],
    connectors: [
      { id: 'gc1', from: 'game-note-1', to: 'game-board-1', fromAnchor: 'bottom', toAnchor: 'top', bend: { x: -40, y: 0 } },
    ],
  },
  'game-chars': {
    title: { es: 'Personajes y Jefes', en: 'Characters & Bosses' },
    parent: 'gamedev',
    parentLabel: { es: 'Project Aether', en: 'Project Aether' },
    items: [
      {
        id: 'game-chars-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Héroes y Enemigos', en: 'Heroes & Enemies' },
      },
      {
        id: 'game-chars-n1', type: 'note', x: 60, y: 130, w: 260, h: 160, color: 'pink',
        content: {
          es: '**VALERY (Protagonista)**\nIngeniera rebelde con brazo prostético de vapor adaptable. Puede equipar cañón, gancho o taladro.',
          en: '**VALERY (Protagonist)**\nRebel engineer with adaptable steam prosthetic arm. Can equip cannon, grapple, or drill.',
        },
      },
      {
        id: 'game-chars-n2', type: 'note', x: 340, y: 130, w: 260, h: 160, color: 'sky',
        content: {
          es: '**EL ALQUIMISTA (Jefe)**\nCientífico corrupto que usa Aether líquido para mutar. Se mueve suspendido por tentáculos mecánicos.',
          en: '**THE ALCHEMIST (Boss)**\nCorrupt scientist who uses liquid Aether to mutate. Moves suspended by mechanical tentacles.',
        },
      },
    ],
    connectors: [],
  },
  'game-mechs': {
    title: { es: 'Mecánicas Core', en: 'Core Mechanics' },
    parent: 'gamedev',
    parentLabel: { es: 'Project Aether', en: 'Project Aether' },
    items: [
      {
        id: 'game-mechs-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Sistemas del Juego', en: 'Game Systems' },
      },
      {
        id: 'game-mechs-n1', type: 'note', x: 60, y: 130, w: 260, h: 150, color: 'mint',
        content: {
          es: '**Presión de Vapor**\nEsquivar y atacar acumula calor. Si se sobrecalienta, Valery inflige más daño pero pierde vida gradualmente.',
          en: '**Steam Pressure**\nDashing and attacking builds up heat. Overheating increases damage output but drains health slowly.',
        },
      },
      {
        id: 'game-mechs-n2', type: 'note', x: 340, y: 130, w: 260, h: 150, color: 'yellow',
        content: {
          es: '**Instalación de Módulos**\nSlots de mejora en bancos de trabajo. Permite optimizar la prótesis para exploración o daño.',
          en: '**Module Upgrades**\nUpgrade slots at workbenches. Allows optimizing the prosthetic for mobility or raw damage.',
        },
      },
    ],
    connectors: [],
  },

  // ─────────── 3. MARKETING ───────────
  'marketing': {
    title: { es: 'Campaña de Marketing — Lanzamiento Nova', en: 'Marketing Campaign — Nova Launch' },
    items: [
      {
        id: 'mkt-note-1', type: 'note', x: 60, y: 130, w: 460, h: 80, color: 'pink',
        content: {
          es: '🚀 **Lanzamiento de Nova SaaS v3.0**\nCampaña de marketing digital multi-canal para posicionar a Nova como el software de colaboración líder en 2026.',
          en: '🚀 **Nova SaaS v3.0 Launch**\nMulti-channel digital marketing campaign to position Nova as the leading collaboration tool in 2026.',
        },
      },
      {
        id: 'mkt-board-1', type: 'board', x: 60, y: 240, w: 260, h: 180, color: 'sky',
        canvasId: 'mkt-channels',
        content: { es: 'Canales y Medios', en: 'Channels & Media' },
      },
      {
        id: 'mkt-board-2', type: 'board', x: 340, y: 240, w: 260, h: 180, color: 'yellow',
        canvasId: 'mkt-creative',
        content: { es: 'Recursos Creativos', en: 'Creative Assets' },
      },
      {
        id: 'mkt-col-1', type: 'column', x: 60, y: 450, w: 280, h: 320, color: 'coral',
        content: { es: 'Fases de Campaña', en: 'Campaign Phases' },
        children: [
          { id: 'mp1', text: { es: 'Fase 1: Teaser en Redes', en: 'Phase 1: Social Teaser' } },
          { id: 'mp2', text: { es: 'Fase 2: Lanzamiento General', en: 'Phase 2: General Release' } },
          { id: 'mp3', text: { es: 'Fase 3: Remarketing', en: 'Phase 3: Remarketing' } },
        ],
      },
      {
        id: 'mkt-todo-1', type: 'todo', x: 360, y: 450, w: 280, h: 220, color: 'yellow',
        title: { es: 'Pre-lanzamiento', en: 'Pre-launch Checklist' },
        items: [
          { id: 'mt1', text: { es: 'Redacción de notas de prensa', en: 'Write press releases' }, done: true },
          { id: 'mt2', text: { es: 'Configurar píxel de conversión', en: 'Set up conversion pixel' }, done: false },
          { id: 'mt3', text: { es: 'Enviar copias de prensa a medios', en: 'Send press kits to media outlets' }, done: false },
        ],
      },
      {
        id: 'mkt-cmt-1', type: 'comment', x: 640, y: 240, w: 260, h: 120,
        avatar: 'E', avatarColor: 'mint',
        name: 'Elisa (Growth)',
        text: {
          es: 'Las campañas de búsqueda de Google Ads deben enfocarse en palabras clave de dolor de usuario.',
          en: 'Google Ads search campaigns should target high-intent user pain points.',
        },
      },
      {
        id: 'mkt-palette', type: 'swatch', x: 640, y: 390, w: 260, h: 140,
        title: { es: 'Branding de Nova', en: 'Nova Branding' },
        colors: [
          { hex: '#FF6B6B', name: 'Coral' },
          { hex: '#4D96FF', name: 'Azul' },
          { hex: '#6BCB77', name: 'Menta' },
          { hex: '#FAF9F6', name: 'Blanco' },
        ],
      },
    ],
    connectors: [
      { id: 'mc1', from: 'mkt-note-1', to: 'mkt-board-1', fromAnchor: 'bottom', toAnchor: 'top', bend: { x: -40, y: 0 } },
    ],
  },
  'mkt-channels': {
    title: { es: 'Canales y Medios', en: 'Channels & Media' },
    parent: 'marketing',
    parentLabel: { es: 'Lanzamiento Nova', en: 'Nova Launch' },
    items: [
      {
        id: 'mkt-chan-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Canales de Adquisición', en: 'Acquisition Channels' },
      },
      {
        id: 'mkt-chan-n1', type: 'note', x: 60, y: 130, w: 260, h: 150, color: 'sky',
        content: {
          es: '**Orgánico e Inbound**\n- Post en el blog sobre silos de comunicación\n- Secuencia de correo para suscriptores\n- SEO enfocado en búsqueda semántica',
          en: '**Organic & Inbound**\n- Blog post on communication silos\n- Email sequence for subscribers\n- SEO optimized for semantic search',
        },
      },
      {
        id: 'mkt-chan-n2', type: 'note', x: 340, y: 130, w: 260, h: 150, color: 'pink',
        content: {
          es: '**Anuncios de Pago**\n- LinkedIn Ads para tomadores de decisiones (CTOs, PMs)\n- Retargeting en YouTube con videos cortos (15s)',
          en: '**Paid Advertising**\n- LinkedIn Ads targeting decision makers (CTOs, PMs)\n- YouTube Ads retargeting with short videos (15s)',
        },
      },
    ],
    connectors: [],
  },
  'mkt-creative': {
    title: { es: 'Recursos Creativos', en: 'Creative Assets' },
    parent: 'marketing',
    parentLabel: { es: 'Lanzamiento Nova', en: 'Nova Launch' },
    items: [
      {
        id: 'mkt-cre-t', type: 'title', x: 60, y: 40, w: 500, h: 60,
        content: { es: 'Recursos de Diseño', en: 'Design Assets' },
      },
      {
        id: 'mkt-cre-n1', type: 'note', x: 60, y: 130, w: 260, h: 140, color: 'yellow',
        content: {
          es: '**Línea Gráfica y Medios**\n- Banners en formatos horizontal y vertical\n- Capturas animadas de la app (GIFs)\n- Videos de testimonios subtitulados',
          en: '**Graphics & Media**\n- Horizontal and vertical banner formats\n- Animated app walkthroughs (GIFs)\n- Subtitled customer testimonial videos',
        },
      },
    ],
    connectors: [],
  },
};

const TRANSLATIONS = {
  es: {
    home_hero: 'Tu mente,\nordenada en\ncanvases.',
    home_sub: 'Odinote es un canvas infinito con tableros anidados. Pensado para game devs, escritores y creativos que no caben en una sola pantalla.',
    new_project: 'Nuevo proyecto',
    search_projects: 'Buscar proyectos…',
    recent: 'Recientes',
    all_projects: 'Todos los proyectos',
    items_count: 'nodos',
    open_board: 'Abrir',
    home: 'Inicio',
    tool_note: 'Nota', tool_link: 'Enlace', tool_todo: 'To-do', tool_line: 'Línea',
    tool_board: 'Tablero', tool_column: 'Columna', tool_comment: 'Comentar',
    tool_image: 'Imagen', tool_doc: 'Documento', tool_calendar: 'Calendario',
    tool_table: 'Tabla', tool_audio: 'Audio',
    tool_color: 'Color', tool_file: 'Archivo',
    search_canvas: 'Buscar en este canvas…',
    new_canvas: 'Nuevo canvas',
  },
  en: {
    home_hero: 'Your mind,\norganized as\ncanvases.',
    home_sub: 'Odinote is an infinite canvas with nested boards. Built for game devs, writers and creatives who don\'t fit on one screen.',
    new_project: 'New project',
    search_projects: 'Search projects…',
    recent: 'Recent',
    all_projects: 'All projects',
    items_count: 'nodes',
    open_board: 'Open',
    home: 'Home',
    tool_note: 'Note', tool_link: 'Link', tool_todo: 'To-do', tool_line: 'Line',
    tool_board: 'Board', tool_column: 'Column', tool_comment: 'Comment',
    tool_image: 'Image', tool_doc: 'Document', tool_calendar: 'Calendar',
    tool_table: 'Table', tool_audio: 'Audio',
    tool_color: 'Color', tool_file: 'File',
    search_canvas: 'Search this canvas…',
    new_canvas: 'New canvas',
  },
  fr: {
    home_hero: 'Votre esprit,\nordonné en\ncanevas.',
    home_sub: 'Odinote est un canevas infini avec des tableaux imbriqués. Conçu pour les développeurs de jeux, écrivains et créatifs.',
    new_project: 'Nouveau projet',
    search_projects: 'Rechercher des projets…',
    recent: 'Récents',
    all_projects: 'Tous les projets',
    items_count: 'nœuds',
    open_board: 'Ouvrir',
    home: 'Accueil',
    tool_note: 'Note', tool_link: 'Lien', tool_todo: 'À faire', tool_line: 'Ligne',
    tool_board: 'Tableau', tool_column: 'Colonne', tool_comment: 'Commentaire',
    tool_image: 'Image', tool_doc: 'Document', tool_calendar: 'Calendrier',
    tool_table: 'Tableau', tool_audio: 'Audio',
    tool_color: 'Couleur', tool_file: 'Fichier',
    search_canvas: 'Rechercher dans ce canevas…',
    new_canvas: 'Nouveau canevas',
  },
  de: {
    home_hero: 'Ihr Geist,\ngeordnet in\nLeinwänden.',
    home_sub: 'Odinote ist eine unendliche Leinwand mit verschachtelten Boards. Entwickelt für Game-Devs, Autoren und Kreative.',
    new_project: 'Neues Projekt',
    search_projects: 'Projekte suchen…',
    recent: 'Verlauf',
    all_projects: 'Alle Projekte',
    items_count: 'Knoten',
    open_board: 'Öffnen',
    home: 'Startseite',
    tool_note: 'Notiz', tool_link: 'Link', tool_todo: 'To-Do', tool_line: 'Linie',
    tool_board: 'Board', tool_column: 'Spalte', tool_comment: 'Kommentar',
    tool_image: 'Bild', tool_doc: 'Dokument', tool_calendar: 'Kalender',
    tool_table: 'Tabelle', tool_audio: 'Audio',
    tool_color: 'Farbe', tool_file: 'Datei',
    search_canvas: 'Auf dieser Leinwand suchen…',
    new_canvas: 'Neue Leinwand',
  },
  it: {
    home_hero: 'La tua mente,\nordinata in\ntavole.',
    home_sub: 'Odinote è una tela infinita con tavole annidate. Pensata per game dev, scrittori e creativi che non entrano in un solo schermo.',
    new_project: 'Nuovo progetto',
    search_projects: 'Cerca progetti…',
    recent: 'Recenti',
    all_projects: 'Tutti i progetti',
    items_count: 'nodi',
    open_board: 'Apri',
    home: 'Inizio',
    tool_note: 'Nota', tool_link: 'Link', tool_todo: 'To-Do', tool_line: 'Linea',
    tool_board: 'Tavola', tool_column: 'Colonna', tool_comment: 'Commento',
    tool_image: 'Immagine', tool_doc: 'Documento', tool_calendar: 'Calendario',
    tool_table: 'Tabella', tool_audio: 'Audio',
    tool_color: 'Colore', tool_file: 'File',
    search_canvas: 'Cerca in questa tela…',
    new_canvas: 'Nuova tela',
  },
  pt: {
    home_hero: 'Sua mente,\norganizada em\ntelas.',
    home_sub: 'Odinote é uma tela infinita com quadros aninhados. Projetado para game devs, escritores e criativos que não cabem em uma só tela.',
    new_project: 'Novo projeto',
    search_projects: 'Buscar projetos…',
    recent: 'Recentes',
    all_projects: 'Todos os projetos',
    items_count: 'nós',
    open_board: 'Abrir',
    home: 'Início',
    tool_note: 'Nota', tool_link: 'Link', tool_todo: 'Lista de tarefas', tool_line: 'Linha',
    tool_board: 'Quadro', tool_column: 'Coluna', tool_comment: 'Comentário',
    tool_image: 'Imagem', tool_doc: 'Documento', tool_calendar: 'Calendário',
    tool_table: 'Tabela', tool_audio: 'Áudio',
    tool_color: 'Cor', tool_file: 'Arquivo',
    search_canvas: 'Buscar nesta tela…',
    new_canvas: 'Nova tela',
  },
  zh: {
    home_hero: '理清思绪，\n尽在无限\n画布。',
    home_sub: 'Odinote 是一个具有嵌套看板的无限画布。专为游戏开发者、作家和创意人员设计。',
    new_project: '新建项目',
    search_projects: '搜索项目…',
    recent: '最近',
    all_projects: '所有项目',
    items_count: '节点',
    open_board: '打开',
    home: '首页',
    tool_note: '便签', tool_link: '链接', tool_todo: '待办事项', tool_line: '连线',
    tool_board: '看板', tool_column: '列栏', tool_comment: '评论',
    tool_image: '图片', tool_doc: '文档', tool_calendar: '日历',
    tool_table: '表格', tool_audio: '音频',
    tool_color: '颜色', tool_file: '文件',
    search_canvas: '在此画布中搜索…',
    new_canvas: '新画布',
  },
  ja: {
    home_hero: '無限のキャンバスで\n思考を整理する。',
    home_sub: 'Odinoteは、ネストされたボードを備えた無限のキャンバスです。ゲーム開発者、作家、クリエイター向けに設計されています。',
    new_project: '新規プロジェクト',
    search_projects: 'プロジェクトを検索…',
    recent: '最近',
    all_projects: 'すべてのプロジェクト',
    items_count: 'ノード',
    open_board: '開く',
    home: 'ホーム',
    tool_note: 'メモ', tool_link: 'リンク', tool_todo: 'ToDo', tool_line: 'ライン',
    tool_board: 'ボード', tool_column: 'カラム', tool_comment: 'コメント',
    tool_image: '画像', tool_doc: 'ドキュメント', tool_calendar: 'カレンダー',
    tool_table: 'テーブル', tool_audio: 'オーディオ',
    tool_color: 'カラー', tool_file: 'ファイル',
    search_canvas: 'このキャンバス内を検索…',
    new_canvas: '新規キャンバス',
  },
  ko: {
    home_hero: '무한한 캔버스에\n당신의 생각을\n정리하세요.',
    home_sub: 'Odinote는 중첩된 보드가 있는 무한 캔버스입니다. 게임 개발자, 작가, 크리에이터를 위해 설계되었습니다.',
    new_project: '새 프로젝트',
    search_projects: '프로젝트 검색…',
    recent: '최근 항목',
    all_projects: '모든 프로젝트',
    items_count: '노드',
    open_board: '열기',
    home: '홈',
    tool_note: '노트', tool_link: '링크', tool_todo: '할 일 목록', tool_line: '선',
    tool_board: '보드', tool_column: '열', tool_comment: '댓글',
    tool_image: '이미지', tool_doc: '문서', tool_calendar: '캘린더',
    tool_table: '표', tool_audio: '오디오',
    tool_color: '색상', tool_file: '파일',
    search_canvas: '캔버스에서 검색…',
    new_canvas: '새 캔버스',
  },
  ar: {
    home_hero: 'رتب أفكارك\nفي لوحات\nمترابطة.',
    home_sub: 'أودينوت هي مساحة لا نهائية تحتوي على لوحات متداخلة. صُممت لمطوري الألعاب والكتاب والمبدعين.',
    new_project: 'مشروع جديد',
    search_projects: 'البحث عن مشاريع…',
    recent: 'المشاريع الأخيرة',
    all_projects: 'جميع المشاريع',
    items_count: 'عناصر',
    open_board: 'فتح',
    home: 'الرئيسية',
    tool_note: 'ملاحظة', tool_link: 'رابط', tool_todo: 'مهام', tool_line: 'خط',
    tool_board: 'لوحة', tool_column: 'عمود', tool_comment: 'تعليق',
    tool_image: 'صورة', tool_doc: 'مستند', tool_calendar: 'تقويم',
    tool_table: 'جدول', tool_audio: 'صوت',
    tool_color: 'لون', tool_file: 'ملف',
    search_canvas: 'البحث في هذه اللوحة…',
    new_canvas: 'لوحة جديدة',
  },
};

Object.assign(window, { SAMPLE_PROJECTS, INITIAL_CANVASES, TRANSLATIONS });

// ==========================================================================
// CENTRALIZED UI WORDS TRANSLATIONS FOR 10 OFFLINE LANGUAGES
// ==========================================================================
window.UI_WORDS = {
  "Atrás": {
    "es": "Atrás",
    "en": "Back",
    "fr": "Retour",
    "de": "Zurück",
    "it": "Indietro",
    "pt": "Voltar",
    "zh": "返回",
    "ja": "戻る",
    "ko": "뒤로",
    "ar": "رجوع"
  },
  "Reacciones": {
    "es": "Reacciones",
    "en": "React",
    "fr": "Réagir",
    "de": "Reagieren",
    "it": "Reazioni",
    "pt": "Reações",
    "zh": "反应",
    "ja": "リアクション",
    "ko": "반응",
    "ar": "تفاعلات"
  },
  "Comentar": {
    "es": "Comentar",
    "en": "Comment",
    "fr": "Commenter",
    "de": "Kommentieren",
    "it": "Commenta",
    "pt": "Comentar",
    "zh": "评论",
    "ja": "コメント",
    "ko": "댓글",
    "ar": "تعليق"
  },
  "Mostrar/ocultar título": {
    "es": "Mostrar/ocultar título",
    "en": "Toggle title",
    "fr": "Afficher/masquer titre",
    "de": "Titel umschalten",
    "it": "Mostra/nascondi titolo",
    "pt": "Mostrar/ocultar título",
    "zh": "显示/隐藏标题",
    "ja": "タイトルの表示切替",
    "ko": "제목 표시 전환",
    "ar": "إظهار/إخفاء العنوان"
  },
  "Título": {
    "es": "Título",
    "en": "Title",
    "fr": "Titre",
    "de": "Titel",
    "it": "Titolo",
    "pt": "Título",
    "zh": "标题",
    "ja": "タイトル",
    "ko": "제목",
    "ar": "العنوان"
  },
  "Fecha límite": {
    "es": "Fecha límite",
    "en": "Due date",
    "fr": "Date limite",
    "de": "Fälligkeitsdatum",
    "it": "Scadenza",
    "pt": "Prazo",
    "zh": "截止日期",
    "ja": "期限",
    "ko": "마감일",
    "ar": "تاريخ الاستحقاق"
  },
  "Para": {
    "es": "Para",
    "en": "Due",
    "fr": "Pour",
    "de": "Fällig",
    "it": "Scadenza",
    "pt": "Para",
    "zh": "截止",
    "ja": "期限",
    "ko": "기한",
    "ar": "مستحق"
  },
  "Asignar": {
    "es": "Asignar",
    "en": "Assign",
    "fr": "Assigner",
    "de": "Zuweisen",
    "it": "Assegna",
    "pt": "Atribuir",
    "zh": "指派",
    "ja": "割り当て",
    "ko": "할당",
    "ar": "تعيين"
  },
  "Aumentar sangría": {
    "es": "Aumentar sangría",
    "en": "Indent",
    "fr": "Augmenter le retrait",
    "de": "Einrücken",
    "it": "Aumenta rientro",
    "pt": "Aumentar recuo",
    "zh": "增加缩进",
    "ja": "インデント",
    "ko": "들여쓰기",
    "ar": "زيادة المسافة البادئة"
  },
  "Indentar": {
    "es": "Indentar",
    "en": "Indent",
    "fr": "Indenter",
    "de": "Einrücken",
    "it": "Rientra",
    "pt": "Indentar",
    "zh": "缩进",
    "ja": "インデント",
    "ko": "들여쓰기",
    "ar": "مسافة بادئة"
  },
  "Reducir sangría": {
    "es": "Reducir sangría",
    "en": "Outdent",
    "fr": "Diminuer le retrait",
    "de": "Ausrücken",
    "it": "Riduci rientro",
    "pt": "Diminuir recuo",
    "zh": "减少缩进",
    "ja": "アウトデント",
    "ko": "내어쓰기",
    "ar": "تقليل المسافة البادئة"
  },
  "Desindentar": {
    "es": "Desindentar",
    "en": "Outdent",
    "fr": "Désindenter",
    "de": "Ausrücken",
    "it": "Riduci rientro",
    "pt": "Desindentar",
    "zh": "减少缩进",
    "ja": "アウトデント",
    "ko": "내어쓰기",
    "ar": "إلغاء المسافة البادئة"
  },
  "Alternar vista previa": {
    "es": "Alternar vista previa",
    "en": "Toggle preview",
    "fr": "Basculer l'aperçu",
    "de": "Vorschau umschalten",
    "it": "Attiva anteprima",
    "pt": "Alternar visualização",
    "zh": "切换预览",
    "ja": "プレビュー切替",
    "ko": "미리보기 전환",
    "ar": "تبديل المعاينة"
  },
  "Vista previa": {
    "es": "Vista previa",
    "en": "Preview",
    "fr": "Aperçu",
    "de": "Vorschau",
    "it": "Anteprima",
    "pt": "Visualização",
    "zh": "预览",
    "ja": "プレビュー",
    "ko": "미리보기",
    "ar": "معاينة"
  },
  "Mostrar informacion": {
    "es": "Mostrar informacion",
    "en": "Show info",
    "fr": "Afficher les infos",
    "de": "Info anzeigen",
    "it": "Mostra informazioni",
    "pt": "Mostrar informações",
    "zh": "显示信息",
    "ja": "情報の表示",
    "ko": "정보 표시",
    "ar": "إظهار المعلومات"
  },
  "Leyenda": {
    "es": "Leyenda",
    "en": "Caption",
    "fr": "Légende",
    "de": "Unterschrift",
    "it": "Didascalia",
    "pt": "Legenda",
    "zh": "说明文字",
    "ja": "キャプション",
    "ko": "캡션",
    "ar": "شرح"
  },
  "Abrir enlace": {
    "es": "Abrir enlace",
    "en": "Open link",
    "fr": "Ouvrir le lien",
    "de": "Link öffnen",
    "it": "Apri link",
    "pt": "Abrir link",
    "zh": "打开链接",
    "ja": "リンクを開く",
    "ko": "링크 열기",
    "ar": "فتح الرابط"
  },
  "Abrir": {
    "es": "Abrir",
    "en": "Open",
    "fr": "Ouvrir",
    "de": "Öffnen",
    "it": "Apri",
    "pt": "Abrir",
    "zh": "打开",
    "ja": "開く",
    "ko": "열기",
    "ar": "فتح"
  },
  "Cambiar icono": {
    "es": "Cambiar icono",
    "en": "Change icon",
    "fr": "Modifier l'icône",
    "de": "Symbol ändern",
    "it": "Cambia icona",
    "pt": "Alterar ícone",
    "zh": "更改图标",
    "ja": "アイコン変更",
    "ko": "아이콘 변경",
    "ar": "تغيير الأيقونة"
  },
  "Icono": {
    "es": "Icono",
    "en": "Icon",
    "fr": "Icône",
    "de": "Symbol",
    "it": "Icona",
    "pt": "Ícone",
    "zh": "图标",
    "ja": "アイコン",
    "ko": "아이콘",
    "ar": "أيقونة"
  },
  "Bucle": {
    "es": "Bucle",
    "en": "Loop",
    "fr": "Boucle",
    "de": "Schleife",
    "it": "Loop",
    "pt": "Loop",
    "zh": "循环",
    "ja": "ループ",
    "ko": "루프",
    "ar": "تكرار"
  },
  "Mostrar HEX": {
    "es": "Mostrar HEX",
    "en": "Show HEX",
    "fr": "Afficher HEX",
    "de": "HEX anzeigen",
    "it": "Mostra HEX",
    "pt": "Mostrar HEX",
    "zh": "显示HEX",
    "ja": "HEX表示",
    "ko": "HEX 표시",
    "ar": "إظهار HEX"
  },
  "Descargar PDF": {
    "es": "Descargar PDF",
    "en": "Download PDF",
    "fr": "Télécharger PDF",
    "de": "PDF herunterladen",
    "it": "Scarica PDF",
    "pt": "Baixar PDF",
    "zh": "下载PDF",
    "ja": "PDFダウンロード",
    "ko": "PDF 다운로드",
    "ar": "تنزيل PDF"
  },
  "Descargar": {
    "es": "Descargar",
    "en": "Download",
    "fr": "Télécharger",
    "de": "Herunterladen",
    "it": "Scarica",
    "pt": "Baixar",
    "zh": "下载",
    "ja": "ダウンロード",
    "ko": "다운로드",
    "ar": "تنزيل"
  },
  "Estilo": {
    "es": "Estilo",
    "en": "Style",
    "fr": "Style",
    "de": "Stil",
    "it": "Stile",
    "pt": "Estilo",
    "zh": "样式",
    "ja": "スタイル",
    "ko": "스타일",
    "ar": "نمط"
  },
  "Fórmula (= en la celda)": {
    "es": "Fórmula (= en la celda)",
    "en": "Formula (= in cell)",
    "fr": "Formule (= dans cellule)",
    "de": "Formel (= in Zelle)",
    "it": "Formula (= nella cella)",
    "pt": "Fórmula (= na célula)",
    "zh": "公式（在单元格中输入 =）",
    "ja": "数式（セル内に=）",
    "ko": "수식 (셀에 = 입력)",
    "ar": "صيغة (= في الخلية)"
  },
  "Fórmula": {
    "es": "Fórmula",
    "en": "Formula",
    "fr": "Formule",
    "de": "Formel",
    "it": "Formula",
    "pt": "Fórmula",
    "zh": "公式",
    "ja": "数式",
    "ko": "수식",
    "ar": "صيغة"
  },
  "Alineación": {
    "es": "Alineación",
    "en": "Alignment",
    "fr": "Alignement",
    "de": "Ausrichtung",
    "it": "Allineamento",
    "pt": "Alinhamento",
    "zh": "对齐",
    "ja": "配置",
    "ko": "정렬",
    "ar": "محاذاة"
  },
  "Align": {
    "es": "Align",
    "en": "Align",
    "fr": "Aligner",
    "de": "Ausrichten",
    "it": "Allinea",
    "pt": "Alinhar",
    "zh": "对齐",
    "ja": "配置",
    "ko": "정렬",
    "ar": "محاذاة"
  },
  "Añadir columna": {
    "es": "Añadir columna",
    "en": "Add column",
    "fr": "Ajouter colonne",
    "de": "Spalte hinzufügen",
    "it": "Aggiungi colonna",
    "pt": "Adicionar coluna",
    "zh": "添加列",
    "ja": "列を追加",
    "ko": "열 추가",
    "ar": "إضافة عمود"
  },
  "Columna": {
    "es": "Columna",
    "en": "Column",
    "fr": "Colonne",
    "de": "Spalte",
    "it": "Colonna",
    "pt": "Coluna",
    "zh": "列",
    "ja": "列",
    "ko": "열",
    "ar": "عمود"
  },
  "Añadir fila": {
    "es": "Añadir fila",
    "en": "Add row",
    "fr": "Ajouter ligne",
    "de": "Zeile hinzufügen",
    "it": "Aggiungi riga",
    "pt": "Adicionar linha",
    "zh": "添加行",
    "ja": "行を追加",
    "ko": "행 추가",
    "ar": "إضافة صف"
  },
  "Eliminar columna": {
    "es": "Eliminar columna",
    "en": "Delete column",
    "fr": "Supprimer colonne",
    "de": "Spalte löschen",
    "it": "Elimina colonna",
    "pt": "Excluir coluna",
    "zh": "删除列",
    "ja": "列を削除",
    "ko": "열 삭제",
    "ar": "حذف العمود"
  },
  "Eliminar fila": {
    "es": "Eliminar fila",
    "en": "Remove row",
    "fr": "Supprimer ligne",
    "de": "Zeile entfernen",
    "it": "Rimuovi riga",
    "pt": "Remover linha",
    "zh": "删除行",
    "ja": "行を削除",
    "ko": "행 제거",
    "ar": "إزالة الصف"
  },
  "Eliminar": {
    "es": "Eliminar",
    "en": "Delete",
    "fr": "Supprimer",
    "de": "Löschen",
    "it": "Elimina",
    "pt": "Excluir",
    "zh": "删除",
    "ja": "削除",
    "ko": "삭제",
    "ar": "حذف"
  },
  "Exportar CSV": {
    "es": "Exportar CSV",
    "en": "Export CSV",
    "fr": "Exporter CSV",
    "de": "CSV exportieren",
    "it": "Esporta CSV",
    "pt": "Exportar CSV",
    "zh": "导出CSV",
    "ja": "CSVエクスポート",
    "ko": "CSV 내보내기",
    "ar": "تصدير CSV"
  },
  "Importar archivo": {
    "es": "Importar archivo",
    "en": "Import file",
    "fr": "Importer fichier",
    "de": "Datei importieren",
    "it": "Importa file",
    "pt": "Importar arquivo",
    "zh": "导入文件",
    "ja": "ファイルをインポート",
    "ko": "파일 가져오기",
    "ar": "استيراد ملف"
  },
  "Exportar": {
    "es": "Exportar",
    "en": "Export",
    "fr": "Exporter",
    "de": "Exportieren",
    "it": "Esporta",
    "pt": "Exportar",
    "zh": "导出",
    "ja": "エクスポート",
    "ko": "내보내기",
    "ar": "تصدير"
  },
  "Importar": {
    "es": "Importar",
    "en": "Import",
    "fr": "Importer",
    "de": "Importieren",
    "it": "Importa",
    "pt": "Importar",
    "zh": "导入",
    "ja": "インポート",
    "ko": "가져오기",
    "ar": "استيراد"
  },
  "Color": {
    "es": "Color",
    "en": "Color",
    "fr": "Couleur",
    "de": "Farbe",
    "it": "Colore",
    "pt": "Cor",
    "zh": "颜色",
    "ja": "色",
    "ko": "색상",
    "ar": "لون"
  },
  "Tamaño": {
    "es": "Tamaño",
    "en": "Size",
    "fr": "Taille",
    "de": "Größe",
    "it": "Dimensione",
    "pt": "Tamanho",
    "zh": "大小",
    "ja": "サイズ",
    "ko": "크기",
    "ar": "حجم"
  },
  "Eliminar nota": {
    "es": "Eliminar nota",
    "en": "Delete note",
    "fr": "Supprimer note",
    "de": "Notiz löschen",
    "it": "Elimina nota",
    "pt": "Excluir nota",
    "zh": "删除便签",
    "ja": "メモを削除",
    "ko": "노트 삭제",
    "ar": "حذف الملاحظة"
  },
  "Eliminar enlace": {
    "es": "Eliminar enlace",
    "en": "Delete link",
    "fr": "Supprimer lien",
    "de": "Link löschen",
    "it": "Elimina link",
    "pt": "Excluir link",
    "zh": "删除链接",
    "ja": "リンクを削除",
    "ko": "링크 삭제",
    "ar": "حذف الرابط"
  },
  "Eliminar tarea": {
    "es": "Eliminar tarea",
    "en": "Delete task",
    "fr": "Supprimer tâche",
    "de": "Aufgabe löschen",
    "it": "Elimina attività",
    "pt": "Excluir tarefa",
    "zh": "删除任务",
    "ja": "タスクを削除",
    "ko": "할 일 삭제",
    "ar": "حذف المهمة"
  },
  "Eliminar conector": {
    "es": "Eliminar conector",
    "en": "Delete connection",
    "fr": "Supprimer connexion",
    "de": "Verbindung löschen",
    "it": "Elimina connessione",
    "pt": "Excluir conexão",
    "zh": "删除连接",
    "ja": "接続を削除",
    "ko": "연결 삭제",
    "ar": "حذف الاتصال"
  },
  "Eliminar tablero": {
    "es": "Eliminar tablero",
    "en": "Delete board",
    "fr": "Supprimer tableau",
    "de": "Board löschen",
    "it": "Elimina tavola",
    "pt": "Excluir quadro",
    "zh": "删除看板",
    "ja": "ボードを削除",
    "ko": "보드 삭제",
    "ar": "حذف اللوحة"
  },
  "Eliminar tabla": {
    "es": "Eliminar tabla",
    "en": "Delete table",
    "fr": "Supprimer tableau",
    "de": "Tabelle löschen",
    "it": "Elimina tabella",
    "pt": "Excluir tabela",
    "zh": "删除表格",
    "ja": "テーブルを削除",
    "ko": "표 삭제",
    "ar": "حذف الجدول"
  },
  "Eliminar calendario": {
    "es": "Eliminar calendario",
    "en": "Delete calendar",
    "fr": "Supprimer calendrier",
    "de": "Kalender löschen",
    "it": "Elimina calendario",
    "pt": "Excluir calendário",
    "zh": "删除日历",
    "ja": "カレンダーを削除",
    "ko": "캘린더 삭제",
    "ar": "حذف التقويم"
  },
  "Eliminar comentario": {
    "es": "Eliminar comentario",
    "en": "Delete comment",
    "fr": "Supprimer commentaire",
    "de": "Kommentar löschen",
    "it": "Elimina commento",
    "pt": "Excluir comentário",
    "zh": "删除评论",
    "ja": "コメントを削除",
    "ko": "댓글 삭제",
    "ar": "حذف التعليق"
  },
  "Eliminar imagen": {
    "es": "Eliminar imagen",
    "en": "Delete image",
    "fr": "Supprimer image",
    "de": "Bild löschen",
    "it": "Elimina immagine",
    "pt": "Excluir imagem",
    "zh": "删除图片",
    "ja": "画像を削除",
    "ko": "이미지 삭제",
    "ar": "حذف الصورة"
  },
  "Eliminar documento": {
    "es": "Eliminar documento",
    "en": "Delete document",
    "fr": "Supprimer document",
    "de": "Dokument löschen",
    "it": "Elimina documento",
    "pt": "Excluir documento",
    "zh": "删除文档",
    "ja": "ドキュメントを削除",
    "ko": "문서 삭제",
    "ar": "حذف المستند"
  },
  "Eliminar archivo": {
    "es": "Eliminar archivo",
    "en": "Delete file",
    "fr": "Supprimer fichier",
    "de": "Datei löschen",
    "it": "Elimina file",
    "pt": "Excluir arquivo",
    "zh": "删除文件",
    "ja": "ファイルを削除",
    "ko": "파일 삭제",
    "ar": "حذف الملف"
  },
  "Eliminar audio": {
    "es": "Eliminar audio",
    "en": "Delete audio",
    "fr": "Supprimer audio",
    "de": "Audio löschen",
    "it": "Elimina audio",
    "pt": "Excluir áudio",
    "zh": "删除音频",
    "ja": "オーディオを削除",
    "ko": "오디오 삭제",
    "ar": "حذف الصوت"
  },
  "Color de fondo del lienzo": {
    "es": "Color de fondo del lienzo",
    "en": "Canvas background color",
    "fr": "Couleur de fond du canevas",
    "de": "Leinwand Hintergrundfarbe",
    "it": "Colore di sfondo della tela",
    "pt": "Cor de fundo da tela",
    "zh": "画布背景颜色",
    "ja": "キャンバスの背景色",
    "ko": "캔버스 배경색",
    "ar": "لون خلفية اللوحة"
  },
  "Fondo del Lienzo": {
    "es": "Fondo del Lienzo",
    "en": "Canvas Background",
    "fr": "Fond du canevas",
    "de": "Leinwand Hintergrund",
    "it": "Sfondo della tela",
    "pt": "Fundo da tela",
    "zh": "画布背景",
    "ja": "キャンバスの背景",
    "ko": "캔버스 배경",
    "ar": "خلفية اللوحة"
  },
  "Cambiar fondo del lienzo": {
    "es": "Cambiar fondo del lienzo",
    "en": "Change canvas background",
    "fr": "Modifier le fond du canevas",
    "de": "Leinwand Hintergrund ändern",
    "it": "Cambia sfondo della tela",
    "pt": "Alterar fundo da tela",
    "zh": "修改画布背景",
    "ja": "キャンバスの背景変更",
    "ko": "캔버스 배경 변경",
    "ar": "تغيير خلفية اللوحة"
  },
  "Curva": {
    "es": "Curva",
    "en": "Curve",
    "fr": "Courbe",
    "de": "Kurve",
    "it": "Curva",
    "pt": "Curva",
    "zh": "曲线",
    "ja": "カーブ",
    "ko": "곡선",
    "ar": "منحنى"
  },
  "Recta": {
    "es": "Recta",
    "en": "Right-angle",
    "fr": "Angle droit",
    "de": "Rechter Winkel",
    "it": "Angolo retto",
    "pt": "Ângulo reto",
    "zh": "直角",
    "ja": "直角",
    "ko": "직각",
    "ar": "زاوية قائمة"
  },
  "Sólida": {
    "es": "Sólida",
    "en": "Solid",
    "fr": "Plein",
    "de": "Durchgehend",
    "it": "Continua",
    "pt": "Sólido",
    "zh": "实线",
    "ja": "実线",
    "ko": "실선",
    "ar": "صلب"
  },
  "Discontinua": {
    "es": "Discontinua",
    "en": "Dashed",
    "fr": "Pointillé",
    "de": "Gestrichelt",
    "it": "Tratteggiata",
    "pt": "Tracejado",
    "zh": "虚线",
    "ja": "破線",
    "ko": "점선",
    "ar": "متقطع"
  },
  "Punteada": {
    "es": "Punteada",
    "en": "Dotted",
    "fr": "Pointillé fin",
    "de": "Gepunktet",
    "it": "Puntinata",
    "pt": "Pontilhado",
    "zh": "点线",
    "ja": "点線",
    "ko": "점선(細)",
    "ar": "منقط"
  },
  "Doble": {
    "es": "Doble",
    "en": "Two-way",
    "fr": "Double sens",
    "de": "Zwei-Wege",
    "it": "Doppio senso",
    "pt": "Duplo sentido",
    "zh": "双向",
    "ja": "双方向",
    "ko": "양방향",
    "ar": "اتجاهين"
  },
  "Flecha bidireccional": {
    "es": "Flecha bidireccional",
    "en": "Bidirectional arrow",
    "fr": "Flèche bidirectionnelle",
    "de": "Bidirektionaler Pfeil",
    "it": "Freccia bidirezionale",
    "pt": "Seta bidirecional",
    "zh": "双向箭头",
    "ja": "双方向矢印",
    "ko": "양방향 화살표",
    "ar": "سهم ثنائي الاتجاه"
  },
  "Etiqueta": {
    "es": "Etiqueta",
    "en": "Label",
    "fr": "Étiquette",
    "de": "Beschriftung",
    "it": "Etichetta",
    "pt": "Etiqueta",
    "zh": "标签",
    "ja": "ラベル",
    "ko": "라벨",
    "ar": "ملصق"
  },
  "Etiqueta…": {
    "es": "Etiqueta…",
    "en": "Label…",
    "fr": "Étiquette…",
    "de": "Beschriftung…",
    "it": "Etichetta…",
    "pt": "Etiqueta…",
    "zh": "标签…",
    "ja": "ラベル…",
    "ko": "라벨…",
    "ar": "ملصق…"
  },
  "Arrastra de un nodo a otro": {
    "es": "Arrastra de un nodo a otro",
    "en": "Drag from one node to another",
    "fr": "Faites glisser d'un nœud à un autre",
    "de": "Von einem Knoten zum anderen ziehen",
    "it": "Trascina da un nodo all'altro",
    "pt": "Arraste de um nó para outro",
    "zh": "从一个节点拖动到另一个节点",
    "ja": "ノードからノードへドラッグ",
    "ko": "한 노드에서 다른 노드로 드래그",
    "ar": "اسحب من عقدة إلى أخرى"
  },
  "Guardado": {
    "es": "Guardado",
    "en": "Saved",
    "fr": "Enregistré",
    "de": "Gespeichert",
    "it": "Salva",
    "pt": "Salvo",
    "zh": "已保存",
    "ja": "保存済",
    "ko": "저장됨",
    "ar": "تم الحفظ"
  },
  "Deshacer": {
    "es": "Deshacer",
    "en": "Undo",
    "fr": "Annuler",
    "de": "Rückgängig machen",
    "it": "Annulla",
    "pt": "Desfazer",
    "zh": "撤销",
    "ja": "元に戻す",
    "ko": "실행 취소",
    "ar": "تراجع"
  },
  "Seleccionar todo": {
    "es": "Seleccionar todo",
    "en": "Select all",
    "fr": "Tout sélectionner",
    "de": "Alles auswählen",
    "it": "Seleziona tutto",
    "pt": "Selecionar tudo",
    "zh": "全选",
    "ja": "すべて選択",
    "ko": "전체 선택",
    "ar": "تحديد الكل"
  },
  "Editar": {
    "es": "Editar",
    "en": "Edit",
    "fr": "Modifier",
    "de": "Bearbeiten",
    "it": "Modifica",
    "pt": "Editar",
    "zh": "编辑",
    "ja": "編集",
    "ko": "편집",
    "ar": "تعديل"
  },
  "Abrir documento": {
    "es": "Abrir documento",
    "en": "Open document",
    "fr": "Ouvrir le document",
    "de": "Dokument öffnen",
    "it": "Apri documento",
    "pt": "Abrir documento",
    "zh": "打开文档",
    "ja": "ドキュメントを開く",
    "ko": "문서 열기",
    "ar": "فتح المستند"
  },
  "Abrir tablero": {
    "es": "Abrir tablero",
    "en": "Open board",
    "fr": "Ouvrir le tableau",
    "de": "Board öffnen",
    "it": "Apri tavola",
    "pt": "Abrir quadro",
    "zh": "打开看板",
    "ja": "ボードを開く",
    "ko": "보드 열기",
    "ar": "فتح اللوحة"
  },
  "Duplicar": {
    "es": "Duplicar",
    "en": "Duplicate",
    "fr": "Dupliquer",
    "de": "Duplizieren",
    "it": "Duplica",
    "pt": "Duplicar",
    "zh": "复制",
    "ja": "複製",
    "ko": "복제",
    "ar": "تكرار"
  },
  "Tú": {
    "es": "Tú",
    "en": "You",
    "fr": "Vous",
    "de": "Du/Sie",
    "it": "Tu",
    "pt": "Você",
    "zh": "你",
    "ja": "あなた",
    "ko": "나",
    "ar": "أنت"
  },
  "Bóveda Local": {
    "es": "Bóveda Local",
    "en": "Local Vault",
    "fr": "Coffre local",
    "de": "Lokaler Safe",
    "it": "Vault locale",
    "pt": "Cofre local",
    "zh": "本地保险库",
    "ja": "ローカル保管庫",
    "ko": "로컬 보관소",
    "ar": "الخزنة المحلية"
  },
  "Desconectar Bóveda": {
    "es": "Desconectar Bóveda",
    "en": "Disconnect Vault",
    "fr": "Déconnecter le coffre",
    "de": "Safe trennen",
    "it": "Disconnetti vault",
    "pt": "Desconectar cofre",
    "zh": "断开保险库",
    "ja": "保管庫の接続解除",
    "ko": "보관소 연결 해제",
    "ar": "إلغاء اتصال الخزنة"
  },
  "Guarda todo directamente en carpetas de tu PC.": {
    "es": "Guarda todo directamente en carpetas de tu PC.",
    "en": "Save everything directly to folders on your PC.",
    "fr": "Enregistrez tout directement dans des dossiers sur votre PC.",
    "de": "Speichern Sie alles direkt in Ordnern auf Ihrem PC.",
    "it": "Salva tutto direttamente nelle cartelle del tuo PC.",
    "pt": "Salve tudo diretamente nas pastas do seu PC.",
    "zh": "将所有内容直接保存到您电脑的文件夹中。",
    "ja": "PC上のフォルダに直接すべてを保存します。",
    "ko": "PC의 폴더에 직접 모든 내용을 저장하세요.",
    "ar": "احفظ كل شيء مباشرة في مجلدات جهاز الكمبيوتر الخاص بك."
  },
  "Abrir Carpeta": {
    "es": "Abrir Carpeta",
    "en": "Open Folder",
    "fr": "Ouvrir le dossier",
    "de": "Ordner öffnen",
    "it": "Apri cartella",
    "pt": "Abrir pasta",
    "zh": "打开文件夹",
    "ja": "フォルダを開く",
    "ko": "폴더 열기",
    "ar": "فتح المجلد"
  },
  "Disponible en la versión de escritorio para PC.": {
    "es": "Disponible en la versión de escritorio para PC.",
    "en": "Available in the desktop version for PC.",
    "fr": "Disponible sur la version de bureau pour PC.",
    "de": "Verfügbar in der Desktop-Version für PC.",
    "it": "Disponibile nella versione desktop per PC.",
    "pt": "Disponível na versão desktop para PC.",
    "zh": "可在PC的桌面版中使用。",
    "ja": "PC向けデスクトップ版でご利用いただけます。",
    "ko": "PC 데스크톱 버전에서 사용 가능합니다.",
    "ar": "متوفر في نسخة سطح المكتب لأجهزة الكمبيوتر."
  },
  "Apoya Odinote": {
    "es": "Apoya Odinote",
    "en": "Support Odinote",
    "fr": "Soutenir Odinote",
    "de": "Odinote unterstützen",
    "it": "Sostieni Odinote",
    "pt": "Apoiar Odinote",
    "zh": "支持 Odinote",
    "ja": "Odinoteをサポート",
    "ko": "Odinote 후원하기",
    "ar": "دعم أودينوت"
  },
  "Odinote es 100% gratis y de código abierto. Si te es útil, considera apoyarnos para mantener el proyecto.": {
    "es": "Odinote es 100% gratis y de código abierto. Si te es útil, considera apoyarnos para mantener el proyecto.",
    "en": "Odinote is 100% free and open source. If you find it useful, consider supporting us to maintain the project.",
    "fr": "Odinote est 100 % gratuit et open source. Si vous le trouvez utile, pensez à nous soutenir.",
    "de": "Odinote ist 100% kostenlos und Open Source. Wenn es Ihnen nützlich ist, unterstützen Sie uns bitte.",
    "it": "Odinote è gratuito al 100% e open source. Se lo trovi utile, considera di sostenerci.",
    "pt": "Odinote é 100% gratuito e de código aberto. Se for útil, considere apoiar-nos.",
    "zh": "Odinote 是 100% 免费且开源的。如果您觉得有用，请考虑支持我们以维持项目。",
    "ja": "Odinoteは100%無料でオープンソースです。便利だと思ったら、プロジェクト継続のために支援をご検討ください。",
    "ko": "Odinote는 100% 무료이며 오픈 소스입니다. 유용하다고 생각하시면 프로젝트 유지를 위한 후원을 고려해 주세요.",
    "ar": "أودينوت مجاني ومفتوح المصدر بنسبة 100٪. إذا كان مفيدًا لك، فيرجى التفكير في دعمنا للاستمرار."
  },
  "Apoyar en Ko-fi": {
    "es": "Apoyar en Ko-fi",
    "en": "Support on Ko-fi",
    "fr": "Soutenir sur Ko-fi",
    "de": "Auf Ko-fi unterstützen",
    "it": "Sostieni su Ko-fi",
    "pt": "Apoiar no Ko-fi",
    "zh": "在 Ko-fi 上支持",
    "ja": "Ko-fiでサポート",
    "ko": "Ko-fi에서 후원하기",
    "ar": "الدعم على Ko-fi"
  },
  "Apoyar": {
    "es": "Apoyar",
    "en": "Support",
    "fr": "Soutenir",
    "de": "Unterstützen",
    "it": "Sostieni",
    "pt": "Apoiar",
    "zh": "支持",
    "ja": "サポート",
    "ko": "후원",
    "ar": "دعم"
  },
  "Apóyame en Ko-fi": {
    "es": "Apóyame en Ko-fi",
    "en": "Support me on Ko-fi",
    "fr": "Soutenez-moi sur Ko-fi",
    "de": "Unterstütze mich auf Ko-fi",
    "it": "Sostienimi su Ko-fi",
    "pt": "Apoie-me no Ko-fi",
    "zh": "在 Ko-fi 上支持我",
    "ja": "Ko-fiで支援する",
    "ko": "Ko-fi에서 저를 후원해 주세요",
    "ar": "ادعمني على Ko-fi"
  },
  "¡Nueva actualización disponible! Haz clic para descargar de GitHub.": {
    "es": "¡Nueva actualización disponible! Haz clic para descargar de GitHub.",
    "en": "New update available! Click to download from GitHub.",
    "fr": "Nouvelle mise à jour disponible ! Cliquez pour télécharger depuis GitHub.",
    "de": "Neue Version verfügbar! Klicken zum Herunterladen von GitHub.",
    "it": "Nuovo aggiornamento disponibile! Clicca per scaricare da GitHub.",
    "pt": "Nova atualização disponível! Clique para baixar do GitHub.",
    "zh": "有新更新可用！点击从 GitHub 下载。",
    "ja": "新しいアップデートがあります！クリックしてGitHubからダウンロードします。",
    "ko": "새로운 업데이트가 있습니다! GitHub에서 다운로드하려면 클릭하세요.",
    "ar": "تحديث جديد متاح! انقر للتنزيل من GitHub."
  },
  "Buscar actualizaciones": {
    "es": "Buscar actualizaciones",
    "en": "Check for updates",
    "fr": "Vérifier les mises à jour",
    "de": "Auf Updates prüfen",
    "it": "Verifica aggiornamenti",
    "pt": "Verificar atualizações",
    "zh": "检查更新",
    "ja": "アップデートを確認",
    "ko": "업데이트 확인",
    "ar": "التحقق من وجود تحديثات"
  },
  "recién": {
    "es": "recién",
    "en": "recent",
    "fr": "récent",
    "de": "vor kurzem",
    "it": "recente",
    "pt": "recente",
    "zh": "最近",
    "ja": "最近",
    "ko": "최근",
    "ar": "حديث"
  },
  "Abrir en navegador": {
    "es": "Abrir en navegador",
    "en": "Open in browser",
    "fr": "Ouvrir dans le navigateur",
    "de": "Im Browser öffnen",
    "it": "Apri nel browser",
    "pt": "Abrir no navegador",
    "zh": "在浏览器中打开",
    "ja": "ブラウザで開く",
    "ko": "브라우저에서 열기",
    "ar": "فتح في المتصفح"
  },
  "Apoyar de forma directa": {
    "es": "Apoyar de forma directa",
    "en": "Direct support",
    "fr": "Soutien direct",
    "de": "Direkte Unterstützung",
    "it": "Supporto diretto",
    "pt": "Apoio direto",
    "zh": "直接支持",
    "ja": "直接支援",
    "ko": "직접 후원",
    "ar": "دعم مباشر"
  },
  "Donadores Recientes": {
    "es": "Donadores Recientes",
    "en": "Recent Donors",
    "fr": "Donateurs récents",
    "de": "Letzte Spender",
    "it": "Donatori recenti",
    "pt": "Doadores recentes",
    "zh": "最近捐赠者",
    "ja": "最近の支援者",
    "ko": "최근 후원자",
    "ar": "المتبرعون المحدثون"
  },
  "Gracias a estas personas por hacer posible Odinote": {
    "es": "Gracias a estas personas por hacer posible Odinote",
    "en": "Thanks to these people for making Odinote possible",
    "fr": "Merci à ces personnes de rendre Odinote possible",
    "de": "Danke an diese Personen, die Odinote möglich machen",
    "it": "Grazie a queste persone per aver reso possibile Odinote",
    "pt": "Agradecemos a estas pessoas por tornarem o Odinote possível",
    "zh": "感谢这些让 Odinote 成为可能的人们",
    "ja": "Odinoteの実現にご協力いただいた皆様に感謝いたします",
    "ko": "Odinote를 가능하게 해주신 분들께 감사드립니다",
    "ar": "شكراً لهؤلاء الأشخاص لجعل أودينوت ممكناً"
  },
  "Añade una leyenda…": {
    "es": "Añade una leyenda…",
    "en": "Add a caption…",
    "fr": "Ajouter une légende…",
    "de": "Beschriftung hinzufügen…",
    "it": "Aggiungi una didascalia…",
    "pt": "Adicione uma legenda…",
    "zh": "添加说明文字…",
    "ja": "キャプションを追加…",
    "ko": "캡션 추가…",
    "ar": "إضافة شرح…"
  },
  "Nuevo tablero": {
    "es": "Nuevo tablero",
    "en": "New board",
    "fr": "Nouveau tableau",
    "de": "Neues Board",
    "it": "Nuova tavola",
    "pt": "Novo quadro",
    "zh": "新看板",
    "ja": "新規ボード",
    "ko": "새 보드",
    "ar": "لوحة جديدة"
  },
  "Nueva tarea": {
    "es": "Nueva tarea",
    "en": "New task",
    "fr": "Nouvelle tâche",
    "de": "Neue Aufgabe",
    "it": "Nuova attività",
    "pt": "Nova tarefa",
    "zh": "新任务",
    "ja": "新規タスク",
    "ko": "새 할 일",
    "ar": "مهمة جديدة"
  },
  "Nueva nota": {
    "es": "Nueva nota",
    "en": "New note",
    "fr": "Nouvelle note",
    "de": "Neue Notiz",
    "it": "Nuova nota",
    "pt": "Nova nota",
    "zh": "新便签",
    "ja": "新規メモ",
    "ko": "새 노트",
    "ar": "ملاحظة جديدة"
  },
  "Nueva columna": {
    "es": "Nueva columna",
    "en": "New column",
    "fr": "Nouvelle colonne",
    "de": "Neue Spalte",
    "it": "Nuova colonna",
    "pt": "Nova coluna",
    "zh": "新列栏",
    "ja": "新規カラム",
    "ko": "새 열",
    "ar": "عمود جديد"
  },
  "Nuevo documento": {
    "es": "Nuevo documento",
    "en": "New document",
    "fr": "Nouveau document",
    "de": "Neues Dokument",
    "it": "Nuovo documento",
    "pt": "Novo documento",
    "zh": "新文档",
    "ja": "新規ドキュメント",
    "ko": "새 문서",
    "ar": "مستند جديد"
  },
  "Nuevo calendario": {
    "es": "Nuevo calendario",
    "en": "New calendar",
    "fr": "Nouveau calendrier",
    "de": "Neuer Kalender",
    "it": "Nuovo calendario",
    "pt": "Novo calendário",
    "zh": "新日历",
    "ja": "新規カレンダー",
    "ko": "새 캘린더",
    "ar": "تقويم جديد"
  },
  "Nueva tabla": {
    "es": "Nueva tabla",
    "en": "New table",
    "fr": "Nouvelle table",
    "de": "Neue Tabelle",
    "it": "Nuova tabella",
    "pt": "Nova tabela",
    "zh": "新表格",
    "ja": "新規テーブル",
    "ko": "새 표",
    "ar": "جدول جديد"
  },
  "Nuevo audio": {
    "es": "Nuevo audio",
    "en": "New audio",
    "fr": "Nouvel audio",
    "de": "Neues Audio",
    "it": "Nuovo audio",
    "pt": "Novo áudio",
    "zh": "新音频",
    "ja": "新規オーディオ",
    "ko": "새 오디오",
    "ar": "صوت جديد"
  },
  "Nuevo enlace": {
    "es": "Nuevo enlace",
    "en": "New link",
    "fr": "Nouveau lien",
    "de": "Neuer Link",
    "it": "Nuovo link",
    "pt": "Novo link",
    "zh": "新链接",
    "ja": "新規リンク",
    "ko": "새 링크",
    "ar": "رابط جديد"
  },
  "Por favor selecciona un archivo de audio válido.": {
    "es": "Por favor selecciona un archivo de audio válido.",
    "en": "Please select a valid audio file.",
    "fr": "Veuillez sélectionner un fichier audio valide.",
    "de": "Bitte wählen Sie eine gültige Audiodatei aus.",
    "it": "Seleziona un file audio valido.",
    "pt": "Por favor, selecione um arquivo de áudio válido.",
    "zh": "请选择有效的音频文件。",
    "ja": "有効なオーディオファイルを選択してください。",
    "ko": "올바른 오디오 파일을 선택해 주세요.",
    "ar": "يرجى تحديد ملف صوتي صالح."
  },
  "Clic para subir un audio": {
    "es": "Clic para subir un audio",
    "en": "Click to upload audio",
    "fr": "Cliquez pour charger un audio",
    "de": "Klicken zum Hochladen einer Audiodatei",
    "it": "Clicca per caricare un file audio",
    "pt": "Clique para carregar um áudio",
    "zh": "点击上传音频",
    "ja": "クリックしてオーディオをアップロード",
    "ko": "오디오를 업로드하려면 클릭하세요",
    "ar": "انقر لتحميل ملف صوتي"
  },
  "No se pudieron comprobar las actualizaciones. Comprueba tu conexión.": {
    "es": "No se pudieron comprobar las actualizaciones. Comprueba tu conexión.",
    "en": "Could not check for updates. Please check your connection.",
    "fr": "Impossible de vérifier les mises à jour. Veuillez vérifier votre connexion.",
    "de": "Updates konnten nicht geprüft werden. Bitte überprüfen Sie Ihre Verbindung.",
    "it": "Impossibile verificare gli aggiornamenti. Controlla la tua connessione.",
    "pt": "Não foi possível verificar as atualizações. Verifique sua conexão.",
    "zh": "无法检查更新。请检查您的网络连接。",
    "ja": "アップデートを確認できませんでした。接続を確認してください。",
    "ko": "업데이트를 확인할 수 없습니다. 연결 상태를 확인해 주세요.",
    "ar": "تعذر التحقق من وجود تحديثات. يرجى التحقق من الاتصال."
  },
  "¡Estás al día! Odinote está en su versión más reciente (v1.0.2).": {
    "es": "¡Estás al día! Odinote está en su versión más reciente (v1.0.2).",
    "en": "You are up to date! Odinote is on the latest version (v1.0.2).",
    "fr": "Vous êtes à jour ! Odinote est dans sa version la plus récente (v1.0.2).",
    "de": "Sie sind auf dem neuesten Stand! Odinote ist in der neuesten Version (v1.0.2).",
    "it": "Sei al passo con gli aggiornamenti! Odinote è all'ultima versione (v1.0.2).",
    "pt": "Você está atualizado! O Odinote está na versão mais recente (v1.0.2).",
    "zh": "您已是最新版本！Odinote 处于最新版本 (v1.0.2)。",
    "ja": "最新の状態です！Odinoteは最新バージョン (v1.0.2) です。",
    "ko": "최신 버전입니다! Odinote가 최신 버전(v1.0.2)입니다.",
    "ar": "أنت على أحدث إصدار! أودينوت في أحدث إصدار (v1.0.2)."
  },
  "No se pudo leer la boveda seleccionada.": {
    "es": "No se pudo leer la boveda seleccionada.",
    "en": "Could not read the selected vault.",
    "fr": "Impossible de lire le coffre sélectionné.",
    "de": "Ausgewählter Safe konnte nicht gelesen werden.",
    "it": "Impossibile leggere il vault selezionato.",
    "pt": "Não foi possível ler o cofre selecionado.",
    "zh": "无法读取所选保险库。",
    "ja": "選択した保管庫を読み取れませんでした。",
    "ko": "선택한 보관소를 읽을 수 없습니다.",
    "ar": "تعذر قراءة الخزنة المحددة."
  },
  "Este archivo no parece ser un respaldo valido de Odinote.": {
    "es": "Este archivo no parece ser un respaldo valido de Odinote.",
    "en": "This file does not look like a valid Odinote backup.",
    "fr": "Ce fichier ne semble pas être une sauvegarde Odinote valide.",
    "de": "Diese Datei scheint kein gültiges Odinote-Backup zu sein.",
    "it": "Questo file non sembra un backup valido di Odinote.",
    "pt": "Este arquivo não parece ser um backup válido do Odinote.",
    "zh": "此文件似乎不是有效的 Odinote 备份文件。",
    "ja": "このファイルは有効なOdinoteバックアップファイルではないようです。",
    "ko": "이 파일은 올바른 Odinote 백업 파일이 아닌 것 같습니다.",
    "ar": "لا يبدو هذا الملف كنسخة احتياطية صالحة لأودينوت."
  },
  "No se pudo importar el respaldo.": {
    "es": "No se pudo importar el respaldo.",
    "en": "The backup could not be imported.",
    "fr": "Impossible d'importer la sauvegarde.",
    "de": "Backup konnte nicht importiert werden.",
    "it": "Impossibile importare il backup.",
    "pt": "Não foi possível importar o backup.",
    "zh": "无法导入备份。",
    "ja": "バックアップをインポートできませんでした。",
    "ko": "백업을 가져올 수 없습니다.",
    "ar": "تعذر استيراد النسخة الاحتياطية."
  }
};

// Translation helper supporting 10 languages reactively
window.t = function(es, en, fr, de, it, pt, zh, ja, ko, ar) {
  const currentLang = window.currentLang || 'es';
  
  // Array parameters support (like dows days of week)
  if (Array.isArray(es)) {
    const list = [es, en, fr, de, it, pt, zh, ja, ko, ar];
    const indexMap = { es: 0, en: 1, fr: 2, de: 3, it: 4, pt: 5, zh: 6, ja: 7, ko: 8, ar: 9 };
    const idx = indexMap[currentLang];
    return list[idx] || list[1] || list[0];
  }

  // If all 10 translations are explicitly passed as arguments:
  if (arguments.length > 2) {
    const indexMap = { es: 0, en: 1, fr: 2, de: 3, it: 4, pt: 5, zh: 6, ja: 7, ko: 8, ar: 9 };
    const idx = indexMap[currentLang];
    return arguments[idx] || en || es;
  }

  // Otherwise, use the global UI_WORDS lookup dictionary
  if (typeof es === 'string') {
    const match = window.UI_WORDS && window.UI_WORDS[es];
    if (match) {
      return match[currentLang] || match.en || match.es || en;
    }
  }
  
  return currentLang === 'es' ? es : en;
};
